
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS title_company text,
  ADD COLUMN IF NOT EXISTS loan_details text,
  ADD COLUMN IF NOT EXISTS llc_information text,
  ADD COLUMN IF NOT EXISTS purchase_price text,
  ADD COLUMN IF NOT EXISTS rehab_amount text,
  ADD COLUMN IF NOT EXISTS estimated_credit_score text,
  ADD COLUMN IF NOT EXISTS estimated_close_date date,
  ADD COLUMN IF NOT EXISTS preferred_lender_id uuid REFERENCES public.contacts(id),
  ADD COLUMN IF NOT EXISTS list_price text,
  ADD COLUMN IF NOT EXISTS town text,
  ADD COLUMN IF NOT EXISTS school_district text,
  ADD COLUMN IF NOT EXISTS contract_price text,
  ADD COLUMN IF NOT EXISTS property_condition text,
  ADD COLUMN IF NOT EXISTS year_built text,
  ADD COLUMN IF NOT EXISTS listing_documents text,
  ADD COLUMN IF NOT EXISTS number_of_units integer,
  ADD COLUMN IF NOT EXISTS unit_mix text,
  ADD COLUMN IF NOT EXISTS cap_rate text,
  ADD COLUMN IF NOT EXISTS noi text,
  ADD COLUMN IF NOT EXISTS zoning text,
  ADD COLUMN IF NOT EXISTS commercial_property_type text,
  ADD COLUMN IF NOT EXISTS investor_deals jsonb DEFAULT '[]'::jsonb;
